CREATE DATABASE IF NOT EXISTS MotoGp;

USE MotoGp;

CREATE TABLE IF NOT EXISTS Fabricantes(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	Nombre VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Modelos(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	Nombre VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Motos(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	FabricanteID INT NOT NULL,
	ModeloID INT NOT NULL,
	FOREIGN KEY (FabricanteID) REFERENCES Fabricantes(ID),
	FOREIGN KEY (ModeloID) REFERENCES Modelos(ID),
	Velocidad INT NOT NULL
);

CREATE TABLE IF NOT EXISTS Motos_Modelo(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	ModeloID INT NOT NULL,
	MotoID INT NOT NULL,
	FOREIGN KEY (ModeloID) REFERENCES Modelos(ID),
	FOREIGN KEY (MotoID) REFERENCES Motos(ID),
	Ano DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS Paises(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	Nombre VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Pilotos(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	Nombre VARCHAR(100),
	FechaNacimiento DATE,
	Victorias INT NOT NULL,
	PaisID INT NOT NULL,
	FOREIGN KEY (PaisID) REFERENCES Paises(ID)
);

CREATE TABLE IF NOT EXISTS Equipos(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	Nombre VARCHAR(100) NOT NULL UNIQUE,
	PaisID INT NOT NULL,
	FabricanteID INT NOT NULL,
	PilotoID INT NOT NULL,
	FOREIGN KEY (PaisID) REFERENCES Paises(ID),
	FOREIGN KEY (FabricanteID) REFERENCES Fabricantes(ID),
	FOREIGN KEY (PilotoID) REFERENCES Pilotos(ID)
);

CREATE TABLE IF NOT EXISTS Climas(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	Nombre VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS Categorias(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	Nombre VARCHAR(100) UNIQUE NOT NULL,
	Cilindraje INT NOT NULL
);


CREATE TABLE IF NOT EXISTS Ubicaciones(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	Nombre VARCHAR(100) NOT NULL,
	PaisID INT NOT NULL,
	FOREIGN KEY (PaisID) REFERENCES Paises(ID)
);

CREATE TABLE IF NOT EXISTS Posiciones(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	Nombre VARCHAR(255) UNIQUE NOT NULL,
	Puntos INT NOT NULL
);

CREATE TABLE IF NOT EXISTS Resultados(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	PosicionID INT NOT NULL,
	PilotoID INT NOT NULL,
	Tiempo TIME NOT NULL,
	FOREIGN KEY (PosicionID) REFERENCES Posiciones(ID),
	FOREIGN KEY (PilotoID) REFERENCES Pilotos(ID)
);

CREATE TABLE IF NOT EXISTS Carreras(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	Nombre VARCHAR(100) NOT NULL,
	Fecha DATE NOT NULL,
	ClimaID INT NOT NULL,
	CategoriaID INT NOT NULL,
	ResultadoID INT NOT NULL,
	UbicacionID INT NOT NULL,
	FOREIGN KEY (ClimaID) REFERENCES Climas(ID),
	FOREIGN KEY (CategoriaID) REFERENCES Categorias(ID),
	FOREIGN KEY (ResultadoID) REFERENCES Resultados(ID),
	FOREIGN KEY (UbicacionID) REFERENCES Ubicaciones(ID)
);

CREATE TABLE IF NOT EXISTS Equipo_Carreras(
	EquipoID INT NOT NULL,
	CarreraID INT NOT NULL,
	FOREIGN KEY (EquipoID) REFERENCES Equipos(ID),
	FOREIGN KEY (CarreraID) REFERENCES Carreras(ID)
);

CREATE TABLE IF NOT EXISTS Circuito(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	Nombre VARCHAR(100) UNIQUE NOT NULL,
	Longitud INT NOT NULL,
	UbicacionID INT NOT NULL,
	Record INT NOT NULL,
	AnoApertura DATE NOT NULL
);
