CREATE DATABASE IF NOT EXISTS MotoGp;

USE MotoGp;

CREATE TABLE IF NOT EXISTS Fabricantes(
	ID INT PRIMARY KEY,
	Nombre VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Modelos(
	ID INT PRIMARY KEY,
	Nombre VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Motos(
	ID INT PRIMARY KEY,
	FabricanteID INT NOT NULL,
	ModeloID INT NOT NULL,
	FOREIGN KEY (FabricanteID) REFERENCES Fabricantes(ID),
	FOREIGN KEY (ModeloID) REFERENCES Modelos(ID),
	Velocidad INT NOT NULL
);

CREATE TABLE IF NOT EXISTS Motos_Modelo(
	ID INT PRIMARY KEY,
	ModeloID INT NOT NULL,
	MotoID INT NOT NULL,
	FOREIGN KEY (ModeloID) REFERENCES Modelos(ID),
	FOREIGN KEY (MotoID) REFERENCES Motos(ID),
	Ano DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS Paises(
	ID INT PRIMARY KEY,
	Nombre VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Pilotos(
	ID INT PRIMARY KEY,
	Nombre VARCHAR(100),
	Apellido VARCHAR(100),
	FechaNacimiento DATE,
	Victorias INT NOT NULL,
	PaisID INT NOT NULL,
	FOREIGN KEY (PaisID) REFERENCES Paises(ID)
);

CREATE TABLE IF NOT EXISTS Equipos(
	ID INT PRIMARY KEY,
	Nombre VARCHAR(100) NOT NULL UNIQUE,
	PaisID INT NOT NULL,
	FabricanteID INT NOT NULL,
	PilotoID INT NOT NULL,
	FOREIGN KEY (PaisID) REFERENCES Paises(ID),
	FOREIGN KEY (FabricanteID) REFERENCES Fabricantes(ID),
	FOREIGN KEY (PilotoID) REFERENCES Pilotos(ID)
);

CREATE TABLE IF NOT EXISTS Climas(
	ID INT PRIMARY KEY,
	Nombre VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS Categorias(
	ID INT PRIMARY KEY,
	Nombre VARCHAR(100) UNIQUE NOT NULL,
	Cilindraje INT NOT NULL
);


CREATE TABLE IF NOT EXISTS Ubicaciones(
	ID INT PRIMARY KEY,
	Nombre VARCHAR(100) NOT NULL,
	PaisID INT NOT NULL,
	FOREIGN KEY (PaisID) REFERENCES Paises(ID)
);

CREATE TABLE IF NOT EXISTS Posiciones(
	ID INT PRIMARY KEY,
	Nombre VARCHAR(255) UNIQUE NOT NULL,
	Puntos INT NOT NULL
);

CREATE TABLE IF NOT EXISTS Resultados(
	ID INT PRIMARY KEY,
	PosicionID INT NOT NULL,
	PilotoID INT NOT NULL,
	Tiempo TIME NOT NULL,
	FOREIGN KEY (PosicionID) REFERENCES Posiciones(ID),
	FOREIGN KEY (PilotoID) REFERENCES Pilotos(ID)
);

CREATE TABLE IF NOT EXISTS Carreras(
	ID INT PRIMARY KEY,
	Nombre VARCHAR(100) NOT NULL,
	Fecha DATE NOT NULL,
	ClimaID INT NOT NULL,
	CategoriaID INT NOT NULL,
	ResultadoID INT NOT NULL,
	UbicacionID INT NOT NULL,
	FOREIGN KEY (ClimaID) REFERENCES Climas(ID),
	FOREIGN KEY (CategoriaID) REFERENCES Categorias(ID),
	FOREIGN KEY (ResultadoID) REFERENCES Resultados(ID),
	FOREIGN KEY (UbicacionID) REFERENCES Ubicaciones(ID)
);

CREATE TABLE IF NOT EXISTS Equipo_Carreras(
	EquipoID INT NOT NULL,
	CarreraID INT NOT NULL,
	FOREIGN KEY (EquipoID) REFERENCES Equipos(ID),
	FOREIGN KEY (CarreraID) REFERENCES Carreras(ID)
);

CREATE TABLE IF NOT EXISTS Circuito(
	ID INT  PRIMARY KEY,
	Nombre VARCHAR(100) UNIQUE NOT NULL,
	Longitud INT NOT NULL,
	UbicacionID INT NOT NULL,
	Record INT NOT NULL,
	AnoApertura DATE NOT NULL
);

-- Inserciones de Fabricantes
INSERT INTO Fabricantes (ID, Nombre)
SELECT 1, 'Yamaha'
WHERE NOT EXISTS (SELECT 1 FROM Fabricantes WHERE ID = 1);

INSERT INTO Fabricantes (ID, Nombre)
SELECT 2, 'Honda'
WHERE NOT EXISTS (SELECT 2 FROM Fabricantes WHERE ID = 2);

INSERT INTO Fabricantes (ID, Nombre)
SELECT 3, 'Ducati'
WHERE NOT EXISTS (SELECT 3 FROM Fabricantes WHERE ID = 3);

INSERT INTO Fabricantes (ID, Nombre)
SELECT 4, 'Suzuki'
WHERE NOT EXISTS (SELECT 4 FROM Fabricantes WHERE ID = 4);

INSERT INTO Fabricantes (ID, Nombre)
SELECT 5, 'KTM'
WHERE NOT EXISTS (SELECT 5 FROM Fabricantes WHERE ID = 5);

INSERT INTO Fabricantes (ID, Nombre)
SELECT 6, 'Asprilia'
WHERE NOT EXISTS (SELECT 6 FROM Fabricantes WHERE ID = 6);

INSERT INTO Fabricantes (ID, Nombre)
SELECT 7, 'BMW'
WHERE NOT EXISTS (SELECT 7 FROM Fabricantes WHERE ID = 7);

INSERT INTO Fabricantes (ID, Nombre)
SELECT 8, 'Kawasaki'
WHERE NOT EXISTS (SELECT 8 FROM Fabricantes WHERE ID = 8);

INSERT INTO Fabricantes (ID, Nombre)
SELECT 9, 'Cagiva'
WHERE NOT EXISTS (SELECT 9 FROM Fabricantes WHERE ID = 9);

INSERT INTO Fabricantes (ID, Nombre)
SELECT 10, 'Norton'
WHERE NOT EXISTS (SELECT 10 FROM Fabricantes WHERE ID = 10);

INSERT INTO Fabricantes (ID, Nombre)
SELECT 11, 'MV Agusta'
WHERE NOT EXISTS (SELECT 11 FROM Fabricantes WHERE ID = 11);

INSERT INTO Fabricantes (ID, Nombre)
SELECT 12, 'Bimota'
WHERE NOT EXISTS (SELECT 12 FROM Fabricantes WHERE ID = 12);

INSERT INTO Fabricantes (ID, Nombre)
SELECT 13, 'Girela'
WHERE NOT EXISTS (SELECT 13 FROM Fabricantes WHERE ID = 13);

INSERT INTO Fabricantes (ID, Nombre)
SELECT 14, 'Scrim'
WHERE NOT EXISTS (SELECT 14 FROM Fabricantes WHERE ID = 14);

INSERT INTO Fabricantes (ID, Nombre)
SELECT 15, 'AJS'
WHERE NOT EXISTS (SELECT 15 FROM Fabricantes WHERE ID = 15);

INSERT INTO Fabricantes (ID, Nombre)
SELECT 16, 'LCR Homda'
WHERE NOT EXISTS (SELECT 16 FROM Fabricantes WHERE ID = 16);

INSERT INTO Fabricantes (ID, Nombre)
SELECT 17, 'Pramac Racing'
WHERE NOT EXISTS (SELECT 17 FROM Fabricantes WHERE ID = 17);

INSERT INTO Fabricantes (ID, Nombre)
SELECT 18, 'Tech3 KTM'
WHERE NOT EXISTS (SELECT 18 FROM Fabricantes WHERE ID = 18);

INSERT INTO Fabricantes (ID, Nombre)
SELECT 19, 'Petronas Yamaha'
WHERE NOT EXISTS (SELECT 19 FROM Fabricantes WHERE ID = 19);

INSERT INTO Fabricantes (ID, Nombre)
SELECT 20, 'Gresini Racing'
WHERE NOT EXISTS (SELECT 20 FROM Fabricantes WHERE ID = 20);
