CREATE DATABASE IF NOT EXISTS MotoGp;

USE MotoGp;

CREATE TABLE IF NOT EXISTS Fabricantes(
	ID INT PRIMARY KEY,
	Nombre VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS Modelos(
	ID INT PRIMARY KEY,
	Nombre VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS Motos(
	ID INT PRIMARY KEY,
	FabricanteID INT,
	ModeloID INT,
	FOREIGN KEY (FabricanteID) REFERENCES Fabricantes(ID),
	FOREIGN KEY (ModeloID) REFERENCES Modelos(ID),
	Velocidad INT
);

CREATE TABLE IF NOT EXISTS Motos_Modelo(
	ID INT PRIMARY KEY,
	ModeloID INT,
	MotoID INT,
	FOREIGN KEY (ModeloID) REFERENCES Modelos(ID),
	FOREIGN KEY (MotoID) REFERENCES Motos(ID),
	Ano DATE
);

CREATE TABLE IF NOT EXISTS Paises(
	ID INT PRIMARY KEY,
	Nombre VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS Pilotos(
	ID INT PRIMARY KEY,
	Nombre VARCHAR(255),
	FechaNacimiento DATE,
	Victorias INT,
	PaisID INT,
	FOREIGN KEY (PaisID) REFERENCES Paises(ID)
);

CREATE TABLE IF NOT EXISTS Equipos(
	ID INT PRIMARY KEY,
	Nombre VARCHAR(255) UNIQUE,
	PaisID INT,
	FabricanteID INT,
	PilotoID INT,
	FOREIGN KEY (PaisID) REFERENCES Paises(ID),
	FOREIGN KEY (FabricanteID) REFERENCES Fabricantes(ID),
	FOREIGN KEY (PilotoID) REFERENCES Pilotos(ID)
);

CREATE TABLE IF NOT EXISTS Climas(
	ID INT PRIMARY KEY,
	Nombre VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS Categorias(
	ID INT PRIMARY KEY,
	Nombre VARCHAR(255) UNIQUE,
	Cilindraje INT
);


CREATE TABLE IF NOT EXISTS Ubicaciones(
	ID INT PRIMARY KEY,
	Nombre VARCHAR(255),
	PaisID INT,
	FOREIGN KEY (PaisID) REFERENCES Paises(ID)
);

CREATE TABLE IF NOT EXISTS Posiciones(
	ID INT PRIMARY KEY,
	Nombre VARCHAR(255) UNIQUE,
	Puntos INT
);

CREATE TABLE IF NOT EXISTS Resultados(
	ID INT PRIMARY KEY,
	PosicionID INT,
	PilotoID INT,
	Tiempo TIME,
	FOREIGN KEY (PosicionID) REFERENCES Posiciones(ID),
	FOREIGN KEY (PilotoID) REFERENCES Pilotos(ID)
);

CREATE TABLE IF NOT EXISTS Carreras(
	ID INT PRIMARY KEY,
	Nombre VARCHAR(255),
	Fecha DATE,
	ClimaID INT,
	CategoriaID INT,
	ResultadoID INT,
	UbicacionID INT,
	FOREIGN KEY (ClimaID) REFERENCES Climas(ID),
	FOREIGN KEY (CategoriaID) REFERENCES Categorias(ID),
	FOREIGN KEY (ResultadoID) REFERENCES Resultados(ID),
	FOREIGN KEY (UbicacionID) REFERENCES Ubicaciones(ID)
);

CREATE TABLE IF NOT EXISTS Equipo_Carreras(
	EquipoID INT,
	CarreraID INT,
	FOREIGN KEY (EquipoID) REFERENCES Equipos(ID),
	FOREIGN KEY (CarreraID) REFERENCES Carreras(ID)
);

CREATE TABLE IF NOT EXISTS Circuito(
	ID INT PRIMARY KEY,
	Nombre VARCHAR(255) UNIQUE,
	Longitud INT,
	UbicacionID INT,
	Record INT,
	AnoApertura DATE
);
